[package]
name = 'termtris'
version = '0.1.0'
authors = ['Christian Steimel <me@C14L.com>']
edition = '2018'

[dependencies]
crossterm = "0.17.4"
rand = "0.7.3"
log = { version = "0.4", features = ["std", "serde"] }
