[package]
name = "termtris"
version = "0.1.0"
authors = ["Christian Steimel <me@C14L.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
